#!/bin/sh

cd /etc/wifi-payment/ || exit 1

npm install || exit 1

sleep 1

CRON='* * * * * /usr/bin/payment-check >/dev/null 2>&1'; grep -Fxq "$CRON" /etc/crontabs/root || { echo "$CRON" >> /etc/crontabs/root; /etc/init.d/cron restart; }

sleep 1

rm -f /etc/uci-defaults/99-whatsapp-bot